version: '3'
services:
  postgres:
    image: postgres:latest
    networks:
      - frontend
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - api
      - client
    ports:
      - 3050:80
    networks:
      - frontend
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    networks:
      - frontend
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
networks:
  frontend: